# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0004_auto_20190307_1423'),
        ('jobs', '0004_auto_20190307_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingpayment', models.DecimalField(decimal_places=2, max_digits=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('is_accepted', models.BooleanField(default=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When this person completed the contact form.', verbose_name='contact date')),
                ('was_contacted', models.BooleanField(default=False, help_text='Check this if someone has already reached out to this person.', verbose_name='has been contacted?')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes relating to contacting this person.', verbose_name='contact notes')),
                ('referer', models.CharField(blank=True, default='', help_text='This is the page the visitor was on before coming to the contact page.', max_length=2048, verbose_name='referring page')),
                ('freelanceprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
                ('jobpaidfor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs')),
                ('paidby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.ProfileJob')),
            ],
        ),
    ]
