# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='project_end_date',
            field=models.DateTimeField(help_text='You need to ad the time when your payment will be transfered to freelancer account', null=True, verbose_name='when will your event end'),
        ),
    ]
