# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-24 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_project_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='project_end_date',
        ),
    ]
