# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-10 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallet_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='enter the date when your project will end.', verbose_name='when will your event end'),
        ),
    ]
